import PageLayout from 'layout/PageLayout';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { Fragment } from 'react';

const Artist = () => {
  const router = useRouter();

  const artistName = router.query.artistName;

  return (
    <Fragment>
      <Head>
        <title>Spotify</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicons/Spotify_Icon_RGB_Green.png' />
      </Head>

      <PageLayout>
        <h1 className='text-white'>Artist name is: {artistName}</h1>
      </PageLayout>
    </Fragment>
  );
};

export default Artist;
