import MusicContainer from 'components/MusicContainer';
import type { GetServerSideProps, NextPage } from 'next';
import { getSession, signOut } from 'next-auth/react';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { Fragment } from 'react';
import PageLayout from '../layout/PageLayout';

const NotFound: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>Spotify</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicons/Spotify_Icon_RGB_Green.png' />
      </Head>

      <PageLayout>
        <div className='h-full flex justify-center items-center'>
          <h1 className='text-[42px] text-[#1ED860]'>Page not found.</h1>
        </div>
      </PageLayout>
    </Fragment>
  );
};

export default NotFound;
