import VerifiedIcon from '@/assets/icons/VerifiedIcon';
import { playlistIdState, playlistState } from 'atoms/playlistAtom';
import useSpotify from 'hooks/useSpotify';
import Header from 'layout/Header';
import PageLayout from 'layout/PageLayout';
import { getToken } from 'next-auth/jwt';
import { useSession } from 'next-auth/react';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import React, { Fragment, useEffect } from 'react';
import { useRecoilState, useRecoilValue, useSetRecoilState } from 'recoil';

const Artist = () => {
  const { data: session, status } = useSession({ required: true });
  const playlistId = useRecoilValue<any>(playlistIdState);
  const [playlist, setPlaylist] = useRecoilState<any>(playlistState);
  const spotifyApi = useSpotify();

  const router = useRouter();
  const artistName = router.query.playlist;

  useEffect(() => {
    spotifyApi
      .getPlaylist(playlistId)
      .then((data) => {
        setPlaylist(data.body);
      })
      .catch((err) => console.error(`Something went wrong ${err} 🔥`));
  }, [spotifyApi, playlistId, setPlaylist]);

  // console.log(playlistId);
  console.log(playlist);

  return (
    <Fragment>
      <Head>
        <title>Spotify</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicons/Spotify_Icon_RGB_Green.png' />
      </Head>

      <PageLayout>
        <main className='h-full'>
          {status === 'loading' ? (
            <div className='h-full flex justify-center items-center'>
              <p>Loading</p>
            </div>
          ) : (
            <div className='h-full relative overflow-y-auto scrollbar-hide'>
              <Header session={session} />

              <div className='h-[calc(100%-60px)]'>
                <div className='relative h-[400px] pl-8 flex items-center gap-7 bg-gradient-to-b from-red-700'>
                  <div className='flex items-center gap-7 '>
                    <div className='h-[230px] w-[230px] relative'>
                      <Image
                        src={
                          playlist && playlist.images
                            ? playlist?.images?.[0]?.url
                            : '/images/artists/Dizzy-dros-banner.png'
                        }
                        layout='fill'
                        objectFit='cover'
                        objectPosition={'bottom'}
                        alt='Artist banner'
                      />
                    </div>

                    <div className='flex flex-col gap-3 self-end'>
                      <div className='flex items-center gap-1'>
                        <VerifiedIcon />
                        <span className='text-white text-sm font-100'>Verified Artist</span>
                      </div>

                      <h1 className='text-[90px] font-400 text-white leading-none'>{artistName}</h1>
                      <span className='text-white font-100 text-base'>
                        113,832 monthly listeners
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}
        </main>
      </PageLayout>
    </Fragment>
  );
};

export default Artist;
