import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { Fragment } from 'react';
import PageLayout from '../layout/PageLayout';
import Sidebar from '../layout/Sidebar';

const Home: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>Spotify</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicons/Spotify_Icon_RGB_Green.png' />
      </Head>

      <PageLayout>
        <main className='bg-[#121212] h-full text-white p-6'>
          <h1>Content Here</h1>

          <Link href={'/login'}>
            <button className='btn'>Login</button>
          </Link>
        </main>
      </PageLayout>
    </Fragment>
  );
};

export default Home;
