import MusicContainer from 'components/MusicContainer';
import type { GetServerSideProps, NextPage } from 'next';
import { getSession, signOut } from 'next-auth/react';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { Fragment } from 'react';
import PageLayout from '../layout/PageLayout';

const Home: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>Spotify</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicons/Spotify_Icon_RGB_Green.png' />
      </Head>

      <PageLayout>
        <MusicContainer />
      </PageLayout>
    </Fragment>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession(context);

  return {
    props: {
      session,
    },
  };
};
